# Generated by Django 3.2 on 2021-04-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100, null=True)),
                ('Age', models.IntegerField()),
                ('Blood_Group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=100)),
                ('phone', models.BigIntegerField()),
                ('city', models.CharField(choices=[('vzm', 'vizianagaram'), ('vskp', 'vizag'), ('sklm', 'srikakulam'), ('vbl', 'bobbili')], max_length=100, null=True)),
            ],
        ),
    ]
