# Generated by Django 3.2 on 2021-04-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
    ]
